--CREATE DATABASE COMPANY
--USE COMPANY
--CREATE TABLE EMPLOYEES(
-- ID INT IDENTITY PRIMARY KEY,
-- FULL_INFO_EMPLOYEE NVARCHAR(60),
-- POSITION_ID INT REFERENCES POSITIONS(ID),
-- SALARY INT,
--)
--CREATE TABLE POSITIONS(
-- ID INT IDENTITY PRIMARY KEY,
-- POSITION_NAME NVARCHAR(30) NOT NULL
--)
--CREATE TABLE BRANCHS(
--ID INT IDENTITY PRIMARY KEY,
-- BRANCH_NAME NVARCHAR(30) NOT NULL
--)
--CREATE TABLE PRODUCTS(
--ID INT IDENTITY PRIMARY KEY,
--NAME NVARCHAR(30) NOT NULL,
--PURCHASE_PRICE INT CHECK (PURCHASE_PRICE>0),
--SALE_PRICE INT CHECK (SALE_PRICE>0)
--)
--CREATE TABLE SELLINGS(
--SELLING_PRODUCT_ID INT REFERENCES PRODUCTS(ID),
--EMPOLYEE_ID INT REFERENCES EMPLOYEES(ID),
--SELL_DATE  datetime DEFAULT getdate() 
--)


--INSERT INTO POSITIONS (POSITION_NAME) VALUES
--('Manager'),
--('Salesperson'),
--('Accountant'),
--('IT Specialist')


--INSERT INTO BRANCHS (BRANCH_NAME) VALUES
--('Headquarters'),
--('Branch 1'),
--('Branch 2'),
--('Branch 3')


--INSERT INTO EMPLOYEES (FULL_INFO_EMPLOYEE, POSITION_ID, SALARY) VALUES
--('John Doe', 1, 50000),
--('Jane Smith', 2, 35000),
--('Bob Johnson', 3, 45000),
--('Alice Brown', 4, 60000)


--INSERT INTO PRODUCTS (NAME, PURCHASE_PRICE, SALE_PRICE) VALUES
--('Console',1360,1500)
--('Laptop', 800, 1200),
--('Smartphone', 500, 800),
--('Printer', 200, 300),
--('Monitor', 300, 500),
--('Keyboard' , 200 , 250),
--('Speaker' , 800 , 1100),
--('Headphones',400,500)



--INSERT INTO SELLINGS (SELLING_PRODUCT_ID, EMPOLYEE_ID) VALUES
--(1, 2),
--(2, 3),
--(3, 1),
--(4, 4),
--(5, 1),
--(6,4),
--(7,3),
--(8,2),

--QUERY 1
--SELECT 
--    EMPLOYEES.FULL_INFO_EMPLOYEE AS EmployeeName,POSITIONS.POSITION_NAME AS Position,BRANCHS.BRANCH_NAME AS Branch,PRODUCTS.NAME AS Product,PRODUCTS.PURCHASE_PRICE AS PurchasePrice,PRODUCTS.SALE_PRICE AS SalePrice
--FROM SELLINGS
--JOIN EMPLOYEES ON SELLINGS.EMPOLYEE_ID = EMPLOYEES.ID 
--JOIN POSITIONS ON EMPLOYEES.POSITION_ID = POSITIONS.ID 
--JOIN PRODUCTS ON SELLINGS.SELLING_PRODUCT_ID = PRODUCTS.ID 
--JOIN BRANCHS ON EMPLOYEES.ID = BRANCHS.ID;


--QUERY 2
--SELECT SUM(SALE_PRICE) AS TotalSales
--FROM PRODUCTS;

-- QUERY 3
--SELECT SUM(PRODUCTS.SALE_PRICE) AS TotalSalesThisMonth
--FROM SELLINGS
--JOIN PRODUCTS ON SELLINGS.SELLING_PRODUCT_ID = PRODUCTS.ID
--WHERE MONTH(SELLINGS.SELL_DATE) = MONTH(GETDATE()) 

----QUERY 4
--SELECT EMPLOYEES.FULL_INFO_EMPLOYEE AS EmployeeName,COUNT(SELLINGS.SELLING_PRODUCT_ID) AS SelledProductCount
--FROM EMPLOYEES LEFT JOIN SELLINGS ON EMPLOYEES.ID = SELLINGS.EMPOLYEE_ID
--GROUP BY EMPLOYEES.ID, EMPLOYEES.FULL_INFO_EMPLOYEE;

--QUERY 5

--SELECT BRANCHS.BRANCH_NAME AS BranchName, COUNT(SELLINGS.SELLING_PRODUCT_ID) AS SoldProductCount
--FROM SELLINGS
--JOIN EMPLOYEES ON SELLINGS.EMPOLYEE_ID = EMPLOYEES.ID 
--JOIN BRANCHS ON EMPLOYEES.ID = BRANCHS.ID
--WHERE CONVERT(DATE, SELLINGS.SELL_DATE) = CONVERT(DATE, GETDATE())
--GROUP BY BRANCHS.BRANCH_NAME
--ORDER BY COUNT(SELLINGS.SELLING_PRODUCT_ID) 

--Query 6

--SELECT PRODUCTS.NAME AS ProductName, COUNT(SELLINGS.SELLING_PRODUCT_ID) AS SoldProductCount
--FROM SELLINGS
--JOIN PRODUCTS ON SELLINGS.SELLING_PRODUCT_ID = PRODUCTS.ID
--WHERE MONTH(SELLINGS.SELL_DATE) = MONTH(GETDATE())
--GROUP BY PRODUCTS.NAME
--ORDER BY COUNT(SELLINGS.SELLING_PRODUCT_ID) 